config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:index]
  end

  resources :albums, only: [:new, :create, :update, :edit, :destroy, :show] do
    resources :tracks, only: [:index]
  end
  
  resources :tracks, only: [:new, :create, :update, :edit, :destroy, :show]
end

app/models/album.rb
class Album < ActiveRecord::Base
  CATEGORIES = %w(live studio)

  validates :title, :year, :genre, :band_id, presence: true
  validates :category, inclusion: {in: CATEGORIES}

  belongs_to :band

  has_many :tracks, dependent: :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy

  # has_many :tracks, dependent: :destroy

end

app/models/track.rb
class Track < ActiveRecord::Base
  CLASS = %w(bonus regular)

  validates :title, :album_id, presence: true
  validates :classification, inclusion: {in: CLASS }

  belongs_to :album
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  after_initialize :ensure_session_token
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: {message: "Password can't be empty"}
  validates :password, length: {minimum: 8, allow_nil: true}

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

def new
  render :new
end

def create
  @album = Album.new(album_params)

  if @album.save
    redirect_to album_url(@album)
  else
    fail
    flash[:errors] = @album.errors.full_messages
    redirect_to new_band_url
  end
end

def show
  @album = Album.find_by(id: params[:id])

  if @album
    render :show
  else
    flash[:errors] = "Album does not exist"
    redirect_to bands_url
  end
end

def edit
  @album = Album.find_by(id: params[:id])

  render :edit

end

def update
  @album = Album.find_by(id: params[:id])

  if @album.update(album_params)
    redirect_to band_url(@album)
  else
    redirect_to bands_url
  end
end

def destroy
  @album = Album.find_by(id: params[:id])
  @album.destroy
  redirect_to bands_url
end

private
def album_params
  params.require(:album).permit(:title, :year, :genre, :category, :band_id)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def auth_token

  end

  def login!(user)
    @current_user = user
    @current_user.reset_session_token!
    session[:session_token] = @current_user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    session[:session_token].nil? ? false : true
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def show
    @band = Band.find_by(id: params[:id])

    if @band
      render :show
    else
      flash[:errors] = "Band does not exist"
      redirect_to bands_url
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])

    render :edit

  end

  def update
    @band = Band.find_by(id: params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      redirect_to bands_url
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
    params[:user][:email],
    params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = "Invalid email and/or password"
      render :new
    else
      login!(user)
      redirect_to bands_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      fail
      flash[:errors] = @track.errors.full_messages
      redirect_to new_band_url
    end
  end

  def show
    @track = Track.find_by(id: params[:id])

    if @track
      render :show
    else
      flash[:errors] = "Track does not exist"
      redirect_to bands_url
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])

    render :edit

  end

  def update
    @track = Track.find_by(id: params[:id])

    if @track.update(track_params)
      redirect_to band_url(@track)
    else
      redirect_to bands_url
    end
  end

  def destroy
    @track = Track.find_by(id: params[:id])
    @track.destroy
    redirect_to bands_url
  end

  private
  def track_params
    params.require(:track).permit(:title, :classification, :lyrics, :album_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to bands_url

    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end

  end

  def show
    @user = User.find_by(id: params[:id])

    if @user
      render :show
    else
      
    end

  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<h1>
  Edit an album!
</h1>


</form>
<section>
  <form action="<%= album_url(@album) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">
    <label for="album_name">Title:</label>
    <input type="text" name="album[title]" value ="<%= @album.title %>" id="album_name" />
    <br>
    <label for="album_year">Year:</label>
    <input type="text" name="album[year]" value ="<%= @album.year %>" id="album_year" />
    <br>
    <label for="album_genre">Genre:</label>
    <input type="text" name="album[genre]" value ="<%= @album.genre %>" id="album_genre" />
    <br>
    <label for="album_band">Band:</label>
    <select name="album[band_id]">
      <option disabled>Please select band name</option>
      <% Band.all.each do |band| %>
        <option value="<%= band.id %>" <%= band.id? ? "selected" : "" %> > <%= band.name %> </option>
      <% end %>

    </select>
    <br>

    <label for="album_category">Category:</label>
      <input type="radio" name="album[category]" value="live" id="album_category" <%= @album.category == "live" ? "checked" : " " %> >Live</input>
      <input type="radio" name="album[category]" value="studio" id="album_category" <%= @album.category == "studio" ? "checked" : " " %> >Studio</input>

    <br>
    <br>

    <input type="submit" value="Edit album!">
  </form>
</section>

app/views/albums/new.html.erb
<h1>
  Add an album!
</h1>

<section>
  <form action="<%= albums_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="album_name">Title:</label>
    <input type="text" name="album[title]" id="album_name" />
    <br>
    <label for="album_year">Year:</label>
    <input type="text" name="album[year]" id="album_year" />
    <br>
    <label for="album_genre">Genre:</label>
    <input type="text" name="album[genre]" id="album_genre" />
    <br>
    <label for="album_band">Band:</label>
    <select name="album[band_id]">
      <option disabled selected = 'selected'>Please select band name</option>
      <% Band.all.each do |band| %>
        <option value="<%= band.id %>"> <%= band.name %> </option>
      <% end %>

    </select>
    <br>

    <label for="album_category">Category:</label>
      <input type="radio" name="album[category]" value="live" id="album_category">Live</input>
      <input type="radio" name="album[category]" value="studio" id="album_category">Studio</input>

    <br>
    <br>

    <input type="submit" value="Add album!">
  </form>
</section>

app/views/albums/show.html.erb
<h1> <%= @album.title %> </h1>

<section>
  <ul>
    <li>
    <% @album.tracks.each do |track| %>
      <a href="../tracks/<%= track.id %>"><%= track.title %></a>
    </li>
    <% end %>

    <li>
      <a href="../tracks/new">Add a new track!</a>

    </li>
  </ul>

</section>

<section>
  <%= button_to 'Edit Album', edit_track_url(@album), method: 'get' %>

  <%= button_to 'Delete Album', album_url(@album), method: 'delete' %>

  <%= button_to 'Return to Band', band_url(@album), method: 'get' %>
</section>

app/views/bands/edit.html.erb
<section>
  <form action="<%= band_url(@band) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <input type="hidden" name="_method" value="PATCH">

    <label for="band_name">Band name:</label>
    <input type="text" name="band[name]" id="band_name" value="<%= @band.name %>" />

    <br>
    <br>

    <input type="submit" value="Edit band!">


  </form>
</section>

app/views/bands/index.html.erb
<h1>Bands</h1>

<ul>
  <li>
  <% @bands.each do |band| %>
    <a href="bands/<%= band.id %>"><%= band.name %></a>
  </li>
  <% end %>
</ul>

app/views/bands/new.html.erb
<header>
  Add a band!
</header>

<section>
  <form action="<%= bands_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="band_name">Band name:</label>
    <input type="text" name="band[name]" id="band_name" />

    <br>
    <br>

    <input type="submit" value="Add band!">
  </form>
</section>

app/views/bands/show.html.erb
<h1> <%= @band.name %> </h1>


<section>
  <ul>
    <li>
    <% @band.albums.each do |album| %>
      <a href="../albums/<%= album.id %>"><%= album.title %></a>
    </li>
    <% end %>

    <li>
      <a href="../albums/new">Add a new album!</a>

    </li>
  </ul>

</section>

<section>
  <%= button_to 'Edit Band', edit_band_url(@band), method: 'get' %>

  <%= button_to 'Delete Band', band_url(@band), method: 'delete' %>

  <%= button_to 'Return to Band Index', bands_url, method: 'get' %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <% if logged_in? %>

      <%= button_to "Logout", "/session", method: 'delete' %>
    <% else %>
      <%= button_to "Sign up!", new_user_url, method: 'get' %>
      <%= button_to "Login!", new_session_url, method: 'get' %>
    <% end %>
  </header>

<%= yield %>

</body>
</html>

app/views/tracks/edit.html.erb
<h1>
  Edit a track!
</h1>


</form>
<section>
  <form action="<%= track_url(@track) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">

    <label for="track_name">Title:</label>
    <input type="text" name="track[title]" id="track_name" value="<%= @track.title %>"/>
    <br>

    <label for="track_album">Album:</label>
    <select name="track[album_id]">
      <option disabled selected = 'selected'>Please select album name</option>
      <% Album.all.each do |album| %>
        <option value="<%= album.id %>" <%= album.id? ? "selected" : "" %> > <%= album.title %> </option>
      <% end %>

    </select>
    <br>

    <label for="track_classification">Classification:</label>
      <input type="radio" name="track[classification]" value="bonus" id="track_classification" <%= @track.classification == "bonus" ? "checked" : " " %> >Bonus</input>
      <input type="radio" name="track[classification]" value="regular" id="track_classification" <%= @track.classification == "regular" ? "checked" : " " %>>Regular</input>

    <br>

    <label for="track_lyrics">Lyrics for Track</label>
    <br>
      <textarea name="track[lyrics]" id="track_lyrics"> <%= @track.lyrics %></textarea>

    <br>

    <input type="submit" value="Edit track!">
  </form>
</section>

app/views/tracks/new.html.erb
<h1>
  Add a track!
</h1>

<section>
  <form action="<%= tracks_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="track_name">Title:</label>
    <input type="text" name="track[title]" id="track_name" />
    <br>

    <label for="track_album">Album:</label>
    <select name="track[album_id]">
      <option disabled selected = 'selected'>Please select album name</option>
      <% Album.all.each do |album| %>
        <option value="<%= album.id %>"> <%= album.title %> </option>
      <% end %>

    </select>
    <br>

    <label for="track_classification">Classification:</label>
      <input type="radio" name="track[classification]" value="bonus" id="track_classification">Bonus</input>
      <input type="radio" name="track[classification]" value="regular" id="track_classification">Regular</input>

    <br>

    <label for="track_lyrics">Lyrics for Track</label>
    <br>
      <textarea name="track[lyrics]" id="track_lyrics"></textarea>

    <br>

    <input type="submit" value="Add track!">
  </form>
</section>

app/views/tracks/show.html.erb
<h1> <%= @track.title %> </h1>

<section>
  <%= button_to 'Edit Track', edit_track_url(@track), method: 'get' %>

  <%= button_to 'Delete Track', track_url(@track), method: 'delete' %>
</section>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MusicApp - Sign Up</title>
  </head>
  <body>
    <h1>Welcome to my Music App!</h1>

    <h3>Please create an account.</h3>

    <section>
      <form action="<%= users_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <label for="user_email">Email:</label>
        <input type="text" name="user[email]" id="user_email" />
        <br>
        <label for="user_password">Password</label>
        <input type="password" name="user[password]" id="user_password" />
        <br>
        <br>

        <input type="submit" value="Sign up!">
      </form>
    </section>

  </body>
</html>

app/views/users/show.html.erb
<section>
  <%= @user.email %>
</section>